server:
  port: 8000

web:
  domain: ${WEB_DOMAIN}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASS}
    url: jdbc:mysql://${DB_HOSTNAME}:${DB_PORT}/${DB_DATABASE}
    type: com.zaxxer.hikari.HikariDataSource