server:
  port: ${PORT:8000}

web:
  domain: ${WEB_DOMAIN}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOSTNAME}:${DB_PORT}/${DB_DATABASE}?currentSchema=${DB_SCHEMA}
    username: ${DB_USER}
    password: ${DB_PASS}