server:
  port: 8000

web:
  domain: http://localhost

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=rngesus
    username: postgres
    password: 4y7sV96vA9wv46VR
