server:
  port: 8080

web:
  domain: http://localhost

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 0809
    url: jdbc:mysql://localhost:3306/rngesus
    type: com.zaxxer.hikari.HikariDataSource